### ISSUE TITLE
process not defined

### ISSUE THREAD

**Issue by sinitsa** [aiji42/remix-emotion-on-cloudflare#1]
I used your patch, thanks it works...!
but i using another template - and i have posted issue there, can you please take a look https://github.com/edmundhung/remix-worker-template/issues/9

i found error line with process.argv... but cannot find package what produce it :(
maybe you have some ideas?
very want to start remix-chakra on cloudflare workers...

**Comment by sinitsa** [comment]
[mf:err] ReferenceError: process is not defined
    at /Users/havok/Work/lawsvc/packages/ccremix/dist/worker.mjs:54:97064
    at /Users/havok/Work/lawsvc/packages/ccremix/dist/worker.mjs:54:97081

who calls process.argv? cannot find any source in node_modules ... very strange :/

**Comment by aiji42** [comment]
@sinitsa
Please provide the minimum configuration repository where the problem occurs and how to reproduce it

**Comment by sinitsa** [comment]
My repository current working https://github.com/sinitsa/ccremix - is based on perfect https://github.com/edmundhung/remix-worker-template with addition of creative-tim template based on chakra-ui, that depends on emotion .....
my current  working repository have some problems because chakra-ui and emotion correctives (https://chakra-ui.com/guides/getting-started/remix-guide) not implemented here ....
how to reproduce bug
just implement this simple guide https://chakra-ui.com/guides/getting-started/remix-guide on my rep .... then, i got an errors, described by you and others, who tried implement emotion cache on cloudflare workers.... stupid bug huh.... and when, i tried your patch - it helps, but then i got an error - process not defined, line with process.argv from somewhere :((

Thanks in advance for your interest)

**Comment by aiji42** [comment]
It was not that difficult a problem.

https://github.com/aiji42/remix-chakra-ui-on-cloudflare/commit/80916aade958871977d92352cc1e912453eec0e4#diff-706f5bbb32fa046dd5e9c3ced01ddffb87e62423d081a5e632717ed01a89ff67
This is my solution.
`process.argv` and `process.cwd` are used in chakra-ui's dependent libraries. If you replace all of them with dummy functions and variables defined in shims, it will work.

Note that the above example uses the latest version of remix and also uses [remix-esbuild-override](https://github.com/aiji42/remix-esbuild-override) to override esbuild.
